steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/wbtg63wxu/hello-world",
        "--build-arg=JAR_FILE=target/hello-world-1.0.0.jar",
        ".",
      ]
images: ["gcr.io/wbtg63wxu/hello-world"]
# mostly taken from https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/maven-example/cloudbuild.yaml
# guide to understand steps - https://cloud.google.com/build/docs/building/build-java
