# openapi2-run.yaml
swagger: "2.0"
info:
  title: demo-1
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Cloud Run hello world
      operationId: hello
      x-google-backend:
        address: https://demo-1-bi7p4glmnq-uk.a.run.app
      responses:
        "200":
          description: A successful response
          schema:
            type: string
# `x-google-backend` should be within path method, this is not the case in GCP doc tutorial
# https://medium.com/google-cloud/secure-cloud-run-cloud-functions-and-app-engine-with-api-key-73c57bededd1
